### Descripción del notebook:

Este notebook tiene la finalidad de crear un conjunto de datos para el proyecto.


Para las url del tipo 'phishing' se ha utilizado PhishTank, la URL para acceder es el siguiente: https://phishtank.org/developer_info.php


Para las url legítimas o benignas se ha utilizado del portal Mendeley Data. En este conjunto contiene tantas url benignas y maliciosas, pero para el proyecto solo nos interesa las urls benignas por lo que se realizará un filtrado. La URL es el siguiente:
https://data.mendeley.com/datasets/gdx3pkwp47/2

Por último para las url del tipo 'malware' y 'defacement', se han utilizado del portal de Kaggle. Igualmente en este conjunto contiene url de otros tipos pero se ha realizado un filtrado para obtener sólo las url del tipo mencionadas, la URL es el siguiente: \
https://www.kaggle.com/datasets/sid321axn/malicious-urls-dataset

In [1]:
import pandas as pd

In [33]:
import warnings
warnings.filterwarnings('ignore')

Subconjunto de URL del tipo phishing

In [11]:
phishing = 'http://data.phishtank.com/data/online-valid.csv.gz'

phish = pd.read_csv(phishing)

In [14]:
print(f"El conjunto phishing tiene {len(phish)} url")

El conjunto phishing tiene 59242 url

Subconjunto de url del tipo benigno

In [15]:
benign = pd.read_csv('Webpages_Classification_train_data.csv')

In [16]:
benign['label'].value_counts()

good    1172747
bad       27253
Name: label, dtype: int64

In [55]:
print("Este conjunto tiene 1.172.747 url del tipo benigno")

Este conjunto tiene 1.172.747 url del tipo benigno

Subconjunto de url de los tipos defacement y malware

In [17]:
malicious = pd.read_csv('malicious_phish-kaggle.csv')

In [18]:
malicious['type'].value_counts()

benign        428103
defacement     96457
phishing       94111
malware        32520
Name: type, dtype: int64

In [56]:
print("Este conjunto tiene aproximadamente 96000 y 32000 url del tipo defacement y malware respectivamente")

Este conjunto tiene aproximadamente 96000 y 32000 url del tipo defacement y malware respectivamente

### Filtrado de los subconjuntos

Filtrar y quedarse solamente con la columna 'url' de cada subconjunto

In [19]:
phish_url = phish[['url']]

In [20]:
phish_url

                                                     url
0      https://docs.google.com/presentation/d/e/2PACX...
1      https://webverify.click/Servicecu/Servicecuorg...
2                             https://www.merluccius.com
3                                      https://honors.cc
4      https://assistenzarenew.bayanihan.ca/it/manage...
...                                                  ...
59237   http://www.ezblox.site/free/jennifer111/helpdesk
59238  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...
59239  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...
59240       http://www.habbocreditosparati.blogspot.com/
59241  http://creditiperhabbogratissicuro100.blogspot...

[59242 rows x 1 columns]

In [21]:
benign_url = benign[benign['label'] == 'good']

In [22]:
benign_url['label'].unique()

array(['good'], dtype=object)

In [57]:
print("Asegurar que unicamente hay url benignas")

Asegurar que unicamente hay url benignas

In [23]:
benign_url = benign_url[['url']]

In [24]:
benign_url

                                               url
0         http://members.tripod.com/russiastation/
1                 http://www.ddj.com/cpp/184403822
2                         http://www.naef-usa.com/
4              http://us.imdb.com/title/tt0176269/
5         http://efilmcritic.com/hbs.cgi?movie=311
...                                            ...
1199995                 http://csrc.nist.gov/rbac/
1199996                  http://www.unm.edu/~hist/
1199997  http://www.syfyportal.com/news423380.html
1199998                    http://www.wardkenpo.ie
1199999  http://homepages.gotadsl.co.uk/~jgm/ekmm/

[1172747 rows x 1 columns]

In [25]:
malware_url = malicious[malicious['type'] == 'malware']

In [26]:
malware_url

                                                      url     type
38      http://www.824555.com/app/member/SportOption.p...  malware
115     http://9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E...  malware
156     http://9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E...  malware
212     http://9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E...  malware
240     http://chinacxyy.com/piccodejs-000.asp?lm2=191...  malware
...                                                   ...      ...
555181                 http://211.137.225.95:47475/Mozi.m  malware
555182                 http://115.55.246.246:44661/Mozi.m  malware
555183                http://219.155.142.211:55621/Mozi.m  malware
555184                   http://42.238.164.8:48848/Mozi.m  malware
555185                   http://172.36.45.82:41684/Mozi.m  malware

[32520 rows x 2 columns]

In [27]:
malware_url = malware_url[['url']]

In [28]:
malware_url

                                                      url
38      http://www.824555.com/app/member/SportOption.p...
115     http://9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E...
156     http://9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E...
212     http://9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E...
240     http://chinacxyy.com/piccodejs-000.asp?lm2=191...
...                                                   ...
555181                 http://211.137.225.95:47475/Mozi.m
555182                 http://115.55.246.246:44661/Mozi.m
555183                http://219.155.142.211:55621/Mozi.m
555184                   http://42.238.164.8:48848/Mozi.m
555185                   http://172.36.45.82:41684/Mozi.m

[32520 rows x 1 columns]

In [29]:
deface_url = malicious[malicious['type'] == 'defacement']

In [30]:
deface_url

                                                      url        type
3       http://www.garage-pirenne.be/index.php?option=...  defacement
4       http://adventure-nicaragua.net/index.php?optio...  defacement
8            http://www.pashminaonline.com/pure-pashminas  defacement
11      http://www.ikenmijnkunst.nl/index.php/expositi...  defacement
13      http://www.lebensmittel-ueberwachung.de/index....  defacement
...                                                   ...         ...
520294  http://blueanchor.nl/dintelmarkt/page/show_cat...  defacement
520302                http://www.hafenrocker.de/index.php  defacement
520305  http://www.kulgupuit.ee/index.php?option=com_p...  defacement
520308   http://www.nhomkinhdep.com/tu-bep-nhom-kinh.html  defacement
520325  http://www.capella.nl/nl.html?view=article&cat...  defacement

[96457 rows x 2 columns]

In [31]:
deface_url = deface_url[['url']]

In [32]:
deface_url

                                                      url
3       http://www.garage-pirenne.be/index.php?option=...
4       http://adventure-nicaragua.net/index.php?optio...
8            http://www.pashminaonline.com/pure-pashminas
11      http://www.ikenmijnkunst.nl/index.php/expositi...
13      http://www.lebensmittel-ueberwachung.de/index....
...                                                   ...
520294  http://blueanchor.nl/dintelmarkt/page/show_cat...
520302                http://www.hafenrocker.de/index.php
520305  http://www.kulgupuit.ee/index.php?option=com_p...
520308   http://www.nhomkinhdep.com/tu-bep-nhom-kinh.html
520325  http://www.capella.nl/nl.html?view=article&cat...

[96457 rows x 1 columns]

### Creación de una nueva columna

Añadir una nueva columna del tipo de url 'type' a cada uno de los subconjuntos

In [34]:
benign_url['type'] = 'benign'
benign_url

                                               url    type
0         http://members.tripod.com/russiastation/  benign
1                 http://www.ddj.com/cpp/184403822  benign
2                         http://www.naef-usa.com/  benign
4              http://us.imdb.com/title/tt0176269/  benign
5         http://efilmcritic.com/hbs.cgi?movie=311  benign
...                                            ...     ...
1199995                 http://csrc.nist.gov/rbac/  benign
1199996                  http://www.unm.edu/~hist/  benign
1199997  http://www.syfyportal.com/news423380.html  benign
1199998                    http://www.wardkenpo.ie  benign
1199999  http://homepages.gotadsl.co.uk/~jgm/ekmm/  benign

[1172747 rows x 2 columns]

In [35]:
malware_url['type'] = 'malware'
malware_url

                                                      url     type
38      http://www.824555.com/app/member/SportOption.p...  malware
115     http://9779.info/%E5%84%BF%E7%AB%A5%E7%AB%8B%E...  malware
156     http://9779.info/%E6%A0%91%E5%8F%B6%E7%B2%98%E...  malware
212     http://9779.info/%E5%8F%A4%E4%BB%A3%E4%BA%8C%E...  malware
240     http://chinacxyy.com/piccodejs-000.asp?lm2=191...  malware
...                                                   ...      ...
555181                 http://211.137.225.95:47475/Mozi.m  malware
555182                 http://115.55.246.246:44661/Mozi.m  malware
555183                http://219.155.142.211:55621/Mozi.m  malware
555184                   http://42.238.164.8:48848/Mozi.m  malware
555185                   http://172.36.45.82:41684/Mozi.m  malware

[32520 rows x 2 columns]

In [36]:
deface_url['type'] = 'defacement'
deface_url

                                                      url        type
3       http://www.garage-pirenne.be/index.php?option=...  defacement
4       http://adventure-nicaragua.net/index.php?optio...  defacement
8            http://www.pashminaonline.com/pure-pashminas  defacement
11      http://www.ikenmijnkunst.nl/index.php/expositi...  defacement
13      http://www.lebensmittel-ueberwachung.de/index....  defacement
...                                                   ...         ...
520294  http://blueanchor.nl/dintelmarkt/page/show_cat...  defacement
520302                http://www.hafenrocker.de/index.php  defacement
520305  http://www.kulgupuit.ee/index.php?option=com_p...  defacement
520308   http://www.nhomkinhdep.com/tu-bep-nhom-kinh.html  defacement
520325  http://www.capella.nl/nl.html?view=article&cat...  defacement

[96457 rows x 2 columns]

In [37]:
phish_url['type'] = 'phishing'
phish_url

                                                     url      type
0      https://docs.google.com/presentation/d/e/2PACX...  phishing
1      https://webverify.click/Servicecu/Servicecuorg...  phishing
2                             https://www.merluccius.com  phishing
3                                      https://honors.cc  phishing
4      https://assistenzarenew.bayanihan.ca/it/manage...  phishing
...                                                  ...       ...
59237   http://www.ezblox.site/free/jennifer111/helpdesk  phishing
59238  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  phishing
59239  http://www.formbuddy.com/cgi-bin/formdisp.pl?u...  phishing
59240       http://www.habbocreditosparati.blogspot.com/  phishing
59241  http://creditiperhabbogratissicuro100.blogspot...  phishing

[59242 rows x 2 columns]

### Extracción de muestras

Extraer 5000 muestras de cada subconjunto con la idea de crear un conjunto de datos balanceado

In [38]:
benign_url = benign_url.sample(n = 5000, random_state=23)
benign_url = benign_url.reset_index(drop=True)

In [39]:
deface_url = deface_url.sample(n = 5000, random_state=23)
deface_url = deface_url.reset_index(drop=True)

In [40]:
malware_url = malware_url.sample(n = 5000, random_state=23)
malware_url = malware_url.reset_index(drop=True)

In [41]:
phish_url = phish_url.sample(n = 5000, random_state=23)
phish_url = phish_url.reset_index(drop=True)

In [42]:
benign_url

                                                    url    type
0     http://www.geocities.com/heartland/ranch/9219/...  benign
1     http://www.humanitiesweb.org/human.php?s=c&amp...  benign
2                            http://www.alixopulos.com/  benign
3                  http://www.pitt.edu/~dash/grimm.html  benign
4                             http://www.intellipdf.com  benign
...                                                 ...     ...
4995                          http://www.zapavision.com  benign
4996                           http://www.niddk.nih.gov  benign
4997                         http://www.truefabric.com/  benign
4998  http://www.geocities.com/hollywood/hills/2653/...  benign
4999                     http://www.fuelforfitness.com/  benign

[5000 rows x 2 columns]

In [43]:
malware_url

                                                    url     type
0     http://hotlinegsm.com/news/7-microsoft-to-drop...  malware
1     https://apbfiber.com/openme/13120d200d42d3_18d...  malware
2                  http://107.158.154.88/bins/Hilix.ppc  malware
3     https://mitsui-jyuku.mixh.jp/uploads/65913687e...  malware
4                        http://69.206.228.124:39922/.i  malware
...                                                 ...      ...
4995  https://mitsui-jyuku.mixh.jp/uploads/708ODNO38...  malware
4996    http://178.128.146.154/beastmode/b3astmode.m68k  malware
4997                   http://37.49.230.241/SBIDIOT/rtk  malware
4998  https://mitsui-jyuku.mixh.jp/uploads/37013687e...  malware
4999  http://9779.info/ppt%E5%89%AA%E8%B4%B4%E7%94%B...  malware

[5000 rows x 2 columns]

In [44]:
phish_url

                                                    url      type
0     https://bafybeiagwpjjm6oxel6fq4shu4b44fdi7sz3c...  phishing
1     http://173-198-247-116.static.as40244.net/wp-a...  phishing
2     https://ipfs.eth.aragon.network/ipfs/bafybeiep...  phishing
3           https://smsorangephonemail.myfreesites.net/  phishing
4     https://aiefjmmvmlaippoctfppa.COom@aiefjmmvmla...  phishing
...                                                 ...       ...
4995  https://docs.google.com/presentation/d/e/2PACX...  phishing
4996  https://ipfs.best-practice.se/ipfs/bafybeid2zg...  phishing
4997                            http://fdju67.pages.dev  phishing
4998         https://ususntfi.top/go/TrackConfirmAction  phishing
4999  https://selvxpsp.elementor.cloud/ENA98765CIZ34...  phishing

[5000 rows x 2 columns]

In [45]:
deface_url

                                                    url        type
0     http://stukkateur-fickinger.de/bilder/2-aussen...  defacement
1     http://www.pn-wuppertal.de/links/2-linkseite/7...  defacement
2     http://www.tortasprimor.cl/index.php?option=co...  defacement
3     http://www.seminariopalafoxiano.com.mx/index.p...  defacement
4        http://www.spbshkaf.ru/catalog/category/divany  defacement
...                                                 ...         ...
4995  http://www.norzwebmarketing.com/it/component/s...  defacement
4996  http://jssk.de/wiki/index.php?title=File:Cnfde...  defacement
4997  http://khangvietdn.com/index.php?option=com_co...  defacement
4998  http://www.caseybrown.co.nz/component/option,c...  defacement
4999  http://www.coleyglesias.com/index.php?option=c...  defacement

[5000 rows x 2 columns]

### Creación del conjunto de datos

Unir los subconjuntos en el conjunto de datos final que se utilizará en el proyecto

In [46]:
dataset_final = pd.concat([benign_url, malware_url, phish_url, deface_url]).reset_index(drop=True)

In [47]:
dataset_final

                                                     url        type
0      http://www.geocities.com/heartland/ranch/9219/...      benign
1      http://www.humanitiesweb.org/human.php?s=c&amp...      benign
2                             http://www.alixopulos.com/      benign
3                   http://www.pitt.edu/~dash/grimm.html      benign
4                              http://www.intellipdf.com      benign
...                                                  ...         ...
19995  http://www.norzwebmarketing.com/it/component/s...  defacement
19996  http://jssk.de/wiki/index.php?title=File:Cnfde...  defacement
19997  http://khangvietdn.com/index.php?option=com_co...  defacement
19998  http://www.caseybrown.co.nz/component/option,c...  defacement
19999  http://www.coleyglesias.com/index.php?option=c...  defacement

[20000 rows x 2 columns]

In [48]:
dataset_final['type'].value_counts()

benign        5000
malware       5000
phishing      5000
defacement    5000
Name: type, dtype: int64

Mezclar las filas del dataset final

In [49]:
dataset_final = dataset_final.sample(frac=1, random_state=23)

Finalmente guardar el dataset creado

In [50]:
dataset_final.to_csv('dataset_final.csv',index=False)

In [51]:
df = pd.read_csv('dataset_final.csv')

In [52]:
df

                                                     url        type
0      http://www.osn-solutions.nl/index.php/nl/over-osn  defacement
1                  http://msb.jcw.mybluehost.me/web.html    phishing
2            https://sites.google.com/view/qwzxvcax/home    phishing
3      https://pub-fc6dc735ff68445cae5ca2d946a8bfbb.r...    phishing
4      https://tinyurl.com/4vz6vmm2/a.html?syl=1x165b...    phishing
...                                                  ...         ...
19995  https://mitsui-jyuku.mixh.jp/uploads/3601q2w3e...     malware
19996  http://www.pubyun.com/wiki/lib/exe/css.php?t=d...     malware
19997         https://bt-mail-service-f245c0.webflow.io/    phishing
19998                  http://111.43.223.83:56977/Mozi.m     malware
19999      http://209.97.130.84/Pandoras_Box/pandora.x86     malware

[20000 rows x 2 columns]

In [53]:
df['type'].value_counts()

defacement    5000
phishing      5000
malware       5000
benign        5000
Name: type, dtype: int64